# Generated by Django 5.2.4 on 2025-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('cancion_id', models.IntegerField()),
                ('duracion_reproducida', models.DurationField()),
                ('porcentaje_escuchado', models.FloatField()),
                ('dispositivo', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('hora_del_dia', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_reproducciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(unique=True)),
                ('generos_favoritos', models.JSONField(default=list)),
                ('artistas_seguidos', models.JSONField(default=list)),
                ('total_reproducciones', models.IntegerField(default=0)),
                ('canciones_gustadas', models.IntegerField(default=0)),
                ('playlists_creadas', models.IntegerField(default=0)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'preferencias_usuario',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionGenerada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('canciones_recomendadas', models.JSONField(default=list)),
                ('algoritmo_usado', models.CharField(max_length=50)),
                ('puntuacion_confianza', models.FloatField()),
                ('valida_hasta', models.DateTimeField()),
                ('generada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recomendaciones_generadas',
                'ordering': ['-generada_en'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRecomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('cancion_recomendada_id', models.IntegerField()),
                ('accion', models.CharField(choices=[('reproducida', 'Reproducida'), ('gustada', 'Le gustó'), ('omitida', 'Omitida'), ('rechazada', 'Rechazada')], max_length=20)),
                ('tiempo_interaccion', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feedback_recomendaciones',
                'unique_together': {('usuario_id', 'cancion_recomendada_id')},
            },
        ),
        migrations.CreateModel(
            name='SimilitudCanciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion_a_id', models.IntegerField()),
                ('cancion_b_id', models.IntegerField()),
                ('puntuacion_similitud', models.FloatField()),
                ('factores_similitud', models.JSONField(default=dict)),
                ('calculada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'similitud_canciones',
                'ordering': ['-puntuacion_similitud'],
                'unique_together': {('cancion_a_id', 'cancion_b_id')},
            },
        ),
    ]
