# Generated by Django 5.2.4 on 2025-07-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('usuario_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'albums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('usuario_id', models.IntegerField()),
                ('es_publica', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'playlists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('cancion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_url', models.URLField()),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario_id', models.IntegerField()),
                ('reproducciones', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('reposts_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones', to='apiPersistencia.album')),
            ],
            options={
                'db_table': 'canciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('usuario_objetivo_id', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('like', 'Like'), ('repost', 'Repost'), ('follow', 'Follow')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='apiPersistencia.cancion')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='apiPersistencia.playlist')),
            ],
            options={
                'db_table': 'interacciones',
                'ordering': ['-created_at'],
                'unique_together': {('usuario_id', 'cancion', 'tipo'), ('usuario_id', 'playlist', 'tipo'), ('usuario_id', 'usuario_objetivo_id', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistCancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='apiPersistencia.cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='apiPersistencia.playlist')),
            ],
            options={
                'db_table': 'playlist_canciones',
                'ordering': ['orden', 'added_at'],
                'unique_together': {('playlist', 'cancion')},
            },
        ),
    ]
