# Generated by Django 5.2.4 on 2025-07-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('termino_busqueda', models.CharField(max_length=255)),
                ('resultados_encontrados', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historial_busqueda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndicesBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(max_length=255, unique=True)),
                ('resultados_canciones', models.JSONField(default=list)),
                ('resultados_playlists', models.JSONField(default=list)),
                ('resultados_usuarios', models.JSONField(default=list)),
                ('frecuencia_busqueda', models.IntegerField(default=1)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'indices_busqueda',
                'ordering': ['-frecuencia_busqueda', '-ultima_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='SugerenciasBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=255, unique=True)),
                ('categoria', models.CharField(choices=[('cancion', 'Canción'), ('playlist', 'Playlist'), ('usuario', 'Usuario'), ('genero', 'Género'), ('album', 'Album')], max_length=50)),
                ('popularidad', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sugerencias_busqueda',
                'ordering': ['-popularidad'],
            },
        ),
    ]
