# Generated by Django 5.2.4 on 2025-07-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Entero'), ('float', 'Número Decimal'), ('boolean', 'Verdadero/Falso'), ('json', 'JSON')], default='string', max_length=20)),
                ('modificable_por_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_sistema',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_usuarios', models.IntegerField(default=0)),
                ('total_canciones', models.IntegerField(default=0)),
                ('total_playlists', models.IntegerField(default=0)),
                ('total_reproducciones_hoy', models.IntegerField(default=0)),
                ('total_reproducciones_mes', models.IntegerField(default=0)),
                ('usuarios_activos_hoy', models.IntegerField(default=0)),
                ('usuarios_activos_mes', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estadisticas_generales',
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload_song', 'Subir Canción'), ('create_playlist', 'Crear Playlist'), ('delete_song', 'Eliminar Canción'), ('delete_playlist', 'Eliminar Playlist'), ('follow_user', 'Seguir Usuario'), ('unfollow_user', 'Dejar de Seguir')], max_length=50)),
                ('detalles', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registro_actividades',
                'ordering': ['-timestamp'],
            },
        ),
    ]
